### ISSUE TITLE
Box indicator is yellow after synthesizing

### ISSUE THREAD

**Issue by corwin-of-amber** [KasraF/LooPy#1]
Immediately following a successful synthesis query, the circular indicator is yellow, which I understand (@nadia-polikarpova told me) tells the user that there is something wrong with the program's execution. But there isn't, this must be some leftover state from when I typed `??`.

<img width="944" alt="Screen Shot 2021-11-29 at 18 14 14" src="https://user-images.githubusercontent.com/704372/143903372-a6f492ef-c304-485b-9e2b-bcc5448a1c82.png">

**Comment by KasraF** [comment]
Yes! This has been a known issue for years now. Thank you for finally pushing me to actually fix it, especially since it took just 2 lines of code. :upside_down_face:

**Comment by corwin-of-amber** [comment]
WTG! 🚀
